#!/bin/sh

if test "x$1" = "xsetup" ; then
  shift
  ./autogen.sh && ./configure $@ && exit 0
elif test "x$1" = "xcleanup" ; then
  test -f Makefile && make distclean
  rm -rf aclocal.m4 autom4te.cache bacon-config.h configure config.* \
    depcomp install-sh missing Makefile stamp-h1 .deps *.in *~ && exit 0
fi

echo "Usage: $0 [setup \${configure options} | cleanup]"
exit 1
